/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as CommishRouteImport } from './routes/commish'
import { Route as IndexRouteImport } from './routes/index'

const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const CommishRoute = CommishRouteImport.update({
  id: '/commish',
  path: '/commish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commish': typeof CommishRoute
  '/picks': typeof PicksRoute
  '/standings': typeof StandingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commish': typeof CommishRoute
  '/picks': typeof PicksRoute
  '/standings': typeof StandingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commish': typeof CommishRoute
  '/picks': typeof PicksRoute
  '/standings': typeof StandingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/commish' | '/picks' | '/standings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/commish' | '/picks' | '/standings'
  id: '__root__' | '/' | '/commish' | '/picks' | '/standings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommishRoute: typeof CommishRoute
  PicksRoute: typeof PicksRoute
  StandingsRoute: typeof StandingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commish': {
      id: '/commish'
      path: '/commish'
      fullPath: '/commish'
      preLoaderRoute: typeof CommishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommishRoute: CommishRoute,
  PicksRoute: PicksRoute,
  StandingsRoute: StandingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
